### ISSUE TITLE
Can you provide the trained model?

### ISSUE THREAD

**Issue by lyres** [NeurAI-Lab/biHomE#1]
Hi,
    Thanks for providing the source code. I want to test your model with my own data. I would be very grateful if you can provide a well-trained model.

**Comment by dkoguciuk** [comment]
Hi @lyres ,

unfortunatelly I am not able to share trained models, however it is really easy to reproduce it. I suggest you use Zeng backbone + biHomE loss trained on PDS-COCO dataset, since this is the most robust configuration:

```
python3 train.py --config_file config/pds-coco/zeng-bihome-lr-1e-3.yaml
```

To use the trained model on your own data you would probably have to write your own dataset.py file, but it should also be really easy if you just copy existing dataset.py file (i.e. `src/data/flir_adas/dataset.py`) and modify it for your case. Please let me know if you have any questions.

Best,
Daniel

**Comment by lyres** [comment]
Thanks for your advice! I will try it soon.
