### ISSUE TITLE
Some questions about FLIR Dataset

### ISSUE THREAD

**Issue by YankeesMolex** [NeurAI-Lab/biHomE#8]
Thank you for your brilliant work, but I have some questions:
(1) As far as I know, the image pairs in the FLIR Dataset dataset are not aligned, how could you calculated the MACE without groundtruth?
(2) In your paper, you said "To test this vulnerability we compare Zhang et al. [44] method with the original and our biHomE loss on FLIR Dataset [7] preprocessed similar to S-COCO."  Could you please provide a more detailed description about this process?
(3) I try to replace the original FLIR dataset with the manually registered dataset (https://github.com/StaRainJ/road-scene-infrared-visible-images), but only the Zeng + Orig strategy can successfully train (maybe because there are too few training data, MACE is only 13 in test data), and the networks of other unsupervised methods cannot converge (loss does not decline, and the value is abnormally large).
I'm confused about how the FLIR experiment in your paper works....

**Comment by dkoguciuk** [comment]
Hi @YankeesMolex ,

1. The S-FLIR Dataset is constructed exactly the same way as the S-COCO dataset: we take a single image, randomly perturb it and those two images are the input to the model and since we created this perturbation by ourselves, we exactly know the gt homography matrix. The process is described in detail in [DeTone's paper](https://arxiv.org/abs/1606.03798) in section 3: **DATA GENERATION FOR HOMOGRAPHY ESTIMATION**. You can find this implemented here: [here](https://github.com/NeurAI-Lab/biHomE/blob/main/src/data/transforms.py#L421).
2. The reason I wanted to test biHomE on the FLIR Dataset is that the images look vastly different than the normal RGB images the loss network was trained on. But as shown in the paper, it turned out that ResNet34 trained on ImageNet can generalize so well, that it can be used as a loss network even for OOD datasets like FLIR. But please note, that here both training and testing images were produced synthetically as described in point 1.
3. Zeng is a heavily supervised approach -- it gets gradients for each pixel and maybe that is the reason why it is working in your case. But, in general, you're trying to solve multimodal registration, which is a very different problem than stated in the biHomE paper, where both input images were the same modality. It is highly likely that you can't just take an off-the-shelf feature extractor and use it as a loss network because the corresponding points won't have the same or very similar feature representation. I think it is still possible to use biHomE-like loss, but you definitely would have to unfreeze it and maybe play around with the architecture a bit.

Best,
Daniel

**Comment by YankeesMolex** [comment]
Hi Daniel,

Thank you for your reply.
I still confused about how the data is generated. 
If the original data of the infrared-visible images have been aligned, I can indeed obtain two images and their GT homology matrix by applying random perturb to one of the images. However, as shown in the figure below, the original images in the FLIR dataset are not aligned, so the homology matrix between images or image patchs can not be obtained in any case. Is this correct?
![11](https://user-images.githubusercontent.com/66425910/165010058-f3d22cfa-2401-4aac-94ce-7409111ebdce.png)

**Comment by dkoguciuk** [comment]
Hi @YankeesMolex ,


> However, as shown in the figure below, the original images in the FLIR dataset are not aligned, so the homology matrix between images or image patchs can not be obtained in any case. Is this correct?


Yes, exactly. Homography can be used for image registration only in two cases: the scene is planar or the camera undergoes rotational movement. Here, both assumptions are violated (AFAIK), thus using tomography to align those images will always give you registration artifacts.

Best,
D

**Comment by 448357739** [comment]
> Hi Daniel,
> 
> Thank you for your reply. I still confused about how the data is generated. If the original data of the infrared-visible images have been aligned, I can indeed obtain two images and their GT homology matrix by applying random perturb to one of the images. However, as shown in the figure below, the original images in the FLIR dataset are not aligned, so the homology matrix between images or image patchs can not be obtained in any case. Is this correct? ![11](https://user-images.githubusercontent.com/66425910/165010058-f3d22cfa-2401-4aac-94ce-7409111ebdce.png)

Hi,I also want to implement pixel registration on FLIR data. Can this method  reach a rough alignment without considering MACE?

**Comment by YankeesMolex** [comment]
> > Hi Daniel,
> > Thank you for your reply. I still confused about how the data is generated. If the original data of the infrared-visible images have been aligned, I can indeed obtain two images and their GT homology matrix by applying random perturb to one of the images. However, as shown in the figure below, the original images in the FLIR dataset are not aligned, so the homology matrix between images or image patchs can not be obtained in any case. Is this correct? ![11](https://user-images.githubusercontent.com/66425910/165010058-f3d22cfa-2401-4aac-94ce-7409111ebdce.png)
> 
> Hi,I also want to implement pixel registration on FLIR data. Can this method reach a rough alignment without considering MACE?

Hi @448357739,

I believe this method doesn't suitable for the rough alignment because it will get a bad result with **severe geometric distortion**. Perhaps a new network architecture should be proposed for rough alignment? Since there is no way to get stable rough alignment registration results in the FLIR dataset, as far as I know.

**Comment by 448357739** [comment]
@YankeesMolex  Thank u.Do you mean that this method is feasible when the multi-modal images are aliged? As far as I know, the aliged visible and infrared dataset can be LLVIP and TARDAL.  But I think that the data distribution of cross-modal data is different, and it is difficult to establish connections between the backgrounds, which is very difficult to match.

**Comment by YankeesMolex** [comment]
> @YankeesMolex Thank u.Do you mean that this method is feasible when the multi-modal images are aliged? As far as I know, the aliged visible and infrared dataset can be LLVIP and TARDAL. But I think that the data distribution of cross-modal data is different, and it is difficult to establish connections between the backgrounds, which is very difficult to match.

Hi @448357739，
I'm not sure about that, however, there are some relative reasearch for cross-modal image registration, such as "Deep
Lucas-Kanade homography for multimodal image alignment". 
In my opinion, how to obtain enough multi-modal image pairs as training data is another difficult problem since most of these methods are supervised.

**Comment by dkoguciuk** [comment]
Hi @448357739 , @YankeesMolex ,

> Hi, I also want to implement pixel registration on FLIR data. Can this method reach a rough alignment without considering MACE?

I think it could work for initial rough alignment, but for sure you would have to unfreeze the loss network here: https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/PerceptualHead.py#L36. However, still using images from the same modality is preferred. 

Best,
D

**Comment by 448357739** [comment]
> I think it could work for initial rough alignment, but for sure you would have to unfreeze the loss network here: https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/PerceptualHead.py#L36. However, still using images from the same modality is preferred.
> 
> Best, D

Thank you. I will try it.
